name: 'Build AZERTY layout with InvertedT nav options for a 3x5 Corne (with Nice Nano v2 + Nice View)'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson:feat/pointers-with-input-processors","zmkfirmware/zmk/main petejohanson:feat/pointers-with-input-processors"]'
